#ifndef configcpp
#define configcpp

#define DETECT_PORT_WAIT_TIME 500
#define SERIAL_WRITE_WAIT 100
#define REMOTE_SERVER_URL "https://malabdali.com/PM/API/"
#define REMOTE_SERVER_ADMIN_NAME "malabdali"
#define REMOTE_SERVER_ADMIN_PASS "mM41634163Mm"
#define UPDATE_DEVICES_GUI_TIMER 500
#define RESEND_TRIES 0
#define NEXT_GCODE_COMMAND_DELAY 200
#define DELAY_BETWEEN_COMMAND_AND_OTHER 500
#define PRINTERS_FOLDER_PATH "./printers"
#define UPLOAD_SUFFIX "G"
#define DEFAULT_Command_No_RESPONSE_TIMEOUT 3000
#define DEVICE_MONITOR_TIMER 5000
#define BUSY_DURATION 10000
#endif
